### ISSUE TITLE
Old Local Start

### ISSUE THREAD

**Issue by ScottGarrison** [moderntribe/square1-global-docker#26] opened 2020-06-18 14:32 UTC
**Describe the bug**
You can no longer start a local project the old way with a global docker, and then in the local project with a `dev/docker/bash start.sh`

**To Reproduce**
- Set up new square1-global-docker
- From anywhere, use `so global:start`
- Go to your local project and start project with `dev/docker/bash start.sh`

**Expected behavior**
Both global and local docker start up correctly.
In browser, the local development site loads

**Actual behavior**
Both global and local docker start up correctly
In browser, the local development site does not load http://p.tri.be/gIXBtR

**System Configuration:**
 - OS: macOS
 - PHP Version 7.3.11

**Comment by jbrinley** [comment] 2020-06-18 14:47
We have removed the bash scripts from the project. Run `so start` in the project directory to start the project.

**Comment by defunctl** [comment] 2020-06-18 18:15
Chatted with Scott on slack, the `jwilder/nginx-proxy` is returning a 499 error and this is likely caused by a certificate mismatch. `so` generates a new CA certificate if it can't find one, and the browser will have an old one. `so global:cert <projectId>.tribe` should fix it before using `/dev/docker/start.sh` on a project without `so` support.

Ideally, the best method is to add and commit a `squareone.yml` to the root of your project so it gets detected as a SquareOne project. Newer versions of `so` will better detect SquareOne Projects.

Place the following in the `squareone.yml` file:

```
# SquareOne Project Docker Config
#
# This file overrides default values from SquareOne Global Docker,
# giving values appropriate to this project for some of the configuration
# variables.
#
# Add variables here if the project requires a different value than the default
# provided by SquareOne Global Docker
#
# See https://github.com/moderntribe/square1-global-docker/blob/master/config/squareone.yml
# for the full list of variables that a project can override. Of particular interest
# are those values under `local-docker` and `tests`
---
```

**Comment by defunctl** [comment] 2020-07-19 23:59
Fixed in https://github.com/moderntribe/square1-global-docker/pull/30

**Closed by defunctl** 2020-07-19 23:59 UTC
Labels: bug
