### ISSUE TITLE
dirname() expects parameter 1 to be string

### ISSUE THREAD

**Issue by mariacdadalt** [moderntribe/square1-global-docker#90] opened 2021-11-04 13:38 UTC
**Describe the bug**
When `so start` fails, every `so` command returns an error.

**To Reproduce**
1) edit the composer.json of the project and make a mistake, for instance, forget a comma in the required list.
2) `so start`
3) fix the composer.json
4) try running `so composer update`, `so restart` or `so stop`

**Expected behavior**
Be able to run the commands after fixing the mistake in the composer file.

**Actual behavior**
The error:
```
In Config.php line 108:
                                                          
  dirname() expects parameter 1 to be string, bool given  
                                                          
```

**System Configuration:**
 - OS: Windows. Running so in WSL2 - Ubuntu
 - PHP Version 7.4.24

**Additional context**
When running the so start I get the following error:                                                               
```
  [Seld\JsonLint\ParsingException]                                  
  "./composer.json" does not contain valid JSON                     
  Parse error on line 103:                                          
  ...dgrid": "2.1.0",  },  "minimum-stabil                          
  --------------------^                                             
  Expected: 'STRING' - It appears you have an extra trailing comma  
   
```                                                                 

- I can run `so` just fine, receiving the list of available commands.

**Comment by defunctl** [comment] 2021-11-04 15:03
@mariacdadalt this error is just passed through from composer itself.

Try bypassing `so` with `so shell` and run composer directly from the container.

**Comment by defunctl** [comment] 2021-11-04 15:05
Ahh I see it also throws and error in `so` itself.

**Comment by defunctl** [comment] 2022-02-17 23:29
Closing this, unable to reproduce and haven't had any other reports and have to assume this was a trailing comma in the `composer.json` it was being run on.

**Closed by defunctl** 2022-02-17 23:29 UTC
Labels: bug
